language: cpp
jobs:
    include:
        - stage: compile
          os: linux
          dist: trusty
          sudo: false
          compiler: gcc
          script: mkdir -p build && cd build/ && cmake -DCMAKE_BUILD_TYPE="Release" .. && cmake --build .
          os: osx
          compiler: clang
          script: mkdir -p build && cd build/ && cmake -DCMAKE_BUILD_TYPE="Release" .. && cmake --build .
