language: cpp
script:
 - mkdir -p build && cd build/
 - cmake -DCMAKE_BUILD_TYPE="Release" ..
 - cmake --build .
matrix:
    include:
        - os: linux
          dist: trusty
          sudo: false
          compiler: gcc
        - os: osx
          compiler: clang

