coverage:
  ignore:
    - "tests/*"
    - "src/parsers/lex.yy.cc"
    - "src/parsers/config_parser.tab.cc"
    - "src/parsers/config_parser.tab.hh"
    - "src/parsers/stack.hh"
    - "src/parsers/location.hh"
    - "src/parsers/position.hh"
    - "src/parsers/config_parser.y"
    - "src/parsers/config_lexer.l"
    - "src/textures/texture_height.hpp"
    - "src/textures/texture_height.cpp"
